(async function(){
 let d=window.SITE_DATA||{};
 const preview=new URLSearchParams(location.search).get('preview')==='1';
 if(preview){try{d=JSON.parse(localStorage.getItem('fr_preview'))||JSON.parse(sessionStorage.getItem('fr_preview'))||d}catch(e){}}
 else{try{const r=await fetch('/api/site-data',{cache:'no-store'});if(r.ok)d=await r.json()}catch(e){}}
 window.LIVE_SITE_DATA=d;
 // V7.1 theme controls.
 const th=d.theme||{};const root=document.documentElement;const themeMap={green:'--green',deep:'--deep',gold:'--gold',silver:'--silver',cream:'--cream',ink:'--ink',white:'--white'};Object.entries(themeMap).forEach(([k,v])=>{if(th[k])root.style.setProperty(v,th[k])});let mt=document.querySelector('meta[name="theme-color"]');if(mt&&th.deep)mt.setAttribute('content',th.deep);
 const dz=d.design||{};root.style.setProperty('--card-radius',(dz.cardRadius??8)+'px');root.style.setProperty('--button-radius',(dz.buttonRadius??4)+'px');root.style.setProperty('--hero-height',(dz.heroHeight||720)+'px');root.style.setProperty('--featured-image-height',(dz.featuredImageHeight||430)+'px');root.style.setProperty('--content-max-width',(dz.contentMaxWidth||1440)+'px');root.style.setProperty('--section-padding',(dz.sectionPadding||90)+'px');root.style.setProperty('--nav-bg',th.navBackground||th.cream||'#F5F2EA');root.style.setProperty('--featured-bg',th.featuredBackground||'#F1E4CE');root.style.setProperty('--community-bg',th.communityBackground||'#DFE5D6');root.style.setProperty('--announcement-bg',th.announcementBackground||th.gold||'#C6A15B');document.body.dataset.heroLayout=dz.heroLayout||'split';document.body.dataset.featuredLayout=dz.featuredLayout||'landscape';document.body.dataset.featuredWidth=dz.featuredWidth||'wide';if(th.backgroundColor)document.body.style.backgroundColor=th.backgroundColor;if(th.backgroundImage){document.body.style.backgroundImage=`url("${String(th.backgroundImage).replace(/"/g,'%22')}")`;document.body.style.backgroundSize=th.backgroundSize||'cover';document.body.style.backgroundPosition=th.backgroundPosition||'center';document.body.style.backgroundAttachment=th.backgroundAttachment||'scroll';document.body.style.backgroundRepeat=th.backgroundSize==='contain'?'repeat':'no-repeat';}
 const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)], txt=(s,v)=>{let e=q(s);if(e&&v!=null)e.textContent=v};let ann=q('.announcement');if(ann){ann.textContent=d.announcement?.text||d.text?.announcement||'';ann.style.display=d.announcement?.enabled===false?'none':'';if(d.announcement?.link){ann.style.cursor='pointer';ann.onclick=()=>location.href=d.announcement.link}}
 // Mark major sections so visibility/order can be controlled.
 const map={hero:'.hero',quick:'.quick',menu:'#menu',featured:'.featured',build:'#build',story:'#story',manifesto:'.manifesto',community:'#community',team:'#team',careers:'#careers',delivery:'#delivery',allergens:'#allergens',visit:'#visit'};
 Object.entries(map).forEach(([id,sel])=>{let e=q(sel);if(e)e.dataset.section=id});
 // Editable public text.
 const t=d.text||{};txt('.announcement',t.announcement);txt('.hero .eyebrow',t.heroEyebrow);let h=q('.hero h1');if(h&&t.heroTitle)h.textContent=t.heroTitle;txt('.hero .lead',t.heroLead);txt('.hero .micro',t.heroMicro);txt('#menu>.eyebrow',t.menuEyebrow);txt('#menu>h2',t.menuTitle);txt('#menu>.intro',t.menuIntro);txt('.featured .eyebrow',t.featuredEyebrow);txt('.featured h2',t.featuredTitle);txt('#build>.eyebrow',`${t.buildEyebrow||'BUILD YOUR OWN'} • £${d.buildYourOwn?.price||'6.99'}`);txt('#build>h2',t.buildTitle);txt('#story .eyebrow',t.storyEyebrow);txt('#story h2',t.storyTitle);if(q('#story .storyText')&&t.storyBody)q('#story .storyText').innerHTML=t.storyBody.split(/\n\s*\n/).map(x=>`<p>${escapeHtml(x)}</p>`).join('');txt('.manifesto p',t.manifesto);txt('#community>.eyebrow',t.communityEyebrow);txt('#community>h2',t.communityTitle);txt('#team>.eyebrow',t.teamEyebrow);txt('#team>h2',t.teamTitle);txt('#delivery .eyebrow',t.deliveryEyebrow);txt('#delivery h2',t.deliveryTitle);txt('#delivery div p:not(.eyebrow)',t.deliveryText);txt('#allergens>.eyebrow',t.allergenEyebrow);txt('#allergens>h2',t.allergenTitle);let ap=q('#allergens>p');if(ap&&t.allergenText)ap.textContent=t.allergenText;txt('#visit>div:first-child .eyebrow',t.findEyebrow);txt('#visit>div:last-child .eyebrow',t.contactEyebrow);txt('#visit>div:last-child h3',t.contactTitle);txt('#visit .muted',t.openingNote);txt('footer>p:nth-of-type(1)',t.footerTagline);
 // Business details.
 qa('[data-business]').forEach(el=>{let k=el.dataset.business;if(d.business?.[k])el.textContent=d.business[k]});let visit=q('#visit');if(visit){let ps=visit.querySelectorAll('div:first-child>p');if(ps[1])ps[1].innerHTML=`<b>Monday–Saturday</b><br>${escapeHtml(d.business?.hours?.Monday||'')}<br><br><b>Sunday</b><br>${escapeHtml(d.business?.hours?.Sunday||'Closed')}`;let em=visit.querySelector('.email');if(em){em.textContent=d.business?.email||'';em.href='mailto:'+(d.business?.email||'')}}
 // Dynamic menu.
 let cards=q('#menu .cards');if(cards&&Array.isArray(d.menu)){cards.innerHTML=d.menu.filter(c=>c.visible!==false).map(c=>`<article><h3>${escapeHtml(c.name)}</h3><p class="muted">${escapeHtml(c.description||'')}</p><ul>${(c.products||[]).filter(p=>p.visible!==false).map(p=>`<li><span>${escapeHtml(p.name)}</span> <b>£${escapeHtml(p.price)}</b>${p.description?`<small class="productDesc">${escapeHtml(p.description)}</small>`:''}</li>`).join('')}</ul></article>`).join('')}
 // Build your own.
 let b=d.buildYourOwn||{},steps=q('#build .steps');if(steps)steps.innerHTML=`<div><span>01</span><h3>Pick a base</h3><p>${(b.bases||[]).map(escapeHtml).join(' • ')}</p></div><div><span>02</span><h3>Pick a main</h3><p>${(b.mains||[]).map(escapeHtml).join(' • ')}</p></div><div><span>03</span><h3>Make it yours</h3><p>${escapeHtml(b.included||'')}</p></div><div><span>04</span><h3>Go extra</h3><p>${escapeHtml(b.extras||'')}</p></div>`;
 // Community.
 let cg=q('#community .communityGrid');if(cg&&Array.isArray(d.community))cg.innerHTML=d.community.map(x=>`<article><b>${escapeHtml(x.title)}</b><p>${escapeHtml(x.text)}</p></article>`).join('');
 // Team and staff images.
 let tg=q('#team .teamGrid'),staff=d.galleries?.staff?.images||[];if(tg&&Array.isArray(d.team))tg.innerHTML=d.team.filter(x=>x.visible!==false).map(x=>{let ims=staff.filter(im=>im.owner===x.id);return `<article class="person">${renderGallery(ims,d.galleries?.staff?.layout||'single','staffGallery')}<h3>${escapeHtml(x.name)}</h3>${x.role&&x.role!==x.name?`<b>${escapeHtml(x.role)}</b>`:''}<p>${escapeHtml(x.description||'')}</p></article>`}).join('');
 // Our Story gallery.
 let story=q('#story');if(story){let old=story.querySelector('.cmsGallery');if(old)old.remove();let g=document.createElement('div');g.className='cmsGallery';g.innerHTML=renderGallery(d.galleries?.ourStory?.images||[],d.galleries?.ourStory?.layout||'collage','storyGallery');story.append(g)}
 // Product gallery / featured visual area.
 let fr=q('.featured .featureRail');if(fr&&(d.galleries?.products?.images||[]).length)fr.innerHTML=renderGallery(d.galleries.products.images,dz.featuredLayout||d.galleries.products.layout||'landscape','productGallery');
 // Delivery buttons.
 let db=q('#delivery .deliveryBtns');if(db){let x=d.delivery||{};db.innerHTML=`<${x.uberEnabled&&x.uberUrl?'a':'button'} ${x.uberEnabled&&x.uberUrl?`href="${escapeAttr(x.uberUrl)}" target="_blank" rel="noopener"`:'disabled'}>${escapeHtml(x.uberLabel||'UBER EATS • COMING SOON')}</${x.uberEnabled&&x.uberUrl?'a':'button'}><${x.justEatEnabled&&x.justEatUrl?'a':'button'} ${x.justEatEnabled&&x.justEatUrl?`href="${escapeAttr(x.justEatUrl)}" target="_blank" rel="noopener"`:'disabled'}>${escapeHtml(x.justEatLabel||'JUST EAT • COMING SOON')}</${x.justEatEnabled&&x.justEatUrl?'a':'button'}>`}
 // V7 hero image.
 let hv=q('.heroVisual');if(hv&&d.hero?.image){hv.innerHTML=`<img class="heroCmsImage" src="${escapeAttr(d.hero.image)}" alt="${escapeAttr(d.hero.alt||'Fresh & Ready by Dori')}" loading="eager">`;hv.classList.add('hasCmsImage');hv.style.setProperty('--hero-position',d.hero.position||'center');hv.style.setProperty('--hero-fit',dz.heroImageFit||'cover');}
 // V7 Careers.
 let cs=q('#careers');if(cs){txt('#careers>.eyebrow',t.careersEyebrow||'CAREERS');txt('#careers>h2',t.careersTitle||'Build brighter days with us.');txt('#careers>.intro',t.careersIntro||'');let list=q('[data-careers-list]'),jobs=Array.isArray(d.careers?.jobs)?d.careers.jobs:[],openJobs=jobs.filter(j=>j&&j.visible!==false&&['open','closing-soon'].includes(String(j.status||'open').trim().toLowerCase()));if(d.careers?.enabled===false){cs.style.display='none'}else if(list){list.innerHTML=openJobs.map(j=>`<article class="careerCard"><span class="careerStatus">${escapeHtml(j.status==='closing-soon'?'Closing soon':'Open')}</span><p class="eyebrow">${escapeHtml(j.department||'CAREERS')}</p><h3>${escapeHtml(j.title||'Vacancy')}</h3><p class="careerMeta">${escapeHtml([j.location,j.employmentType,j.hours,j.pay].filter(Boolean).join(' • '))}</p><p>${escapeHtml(j.summary||'')}</p><a class="textLink" href="careers.html?job=${encodeURIComponent(j.id)}">View role & apply →</a></article>`).join('')||'<p class="muted">No vacancies are currently published.</p>';}}
 // Section visibility + order within main.
 let main=q('main');if(main&&Array.isArray(d.sections))d.sections.forEach(s=>{let e=q(`[data-section="${CSS.escape(s.id)}"]`);if(e){if(s.id==='careers'){e.style.display=d.careers?.enabled===false?'none':'';}else{e.style.display=s.visible===false?'none':'';}main.appendChild(e)}});
 // Careers visibility is owned by Careers settings, not legacy Sections state.
 if(cs) cs.style.display=d.careers?.enabled===false?'none':'';
 if(dz.showMobileBar!==false&&!document.querySelector('.mobileQuickBar')){let mb=document.createElement('nav');mb.className='mobileQuickBar';mb.innerHTML='<a href="#menu">MENU</a><a href="#build">BUILD YOUR OWN</a><a href="#delivery">ORDER</a>';document.body.appendChild(mb)}
 function escapeHtml(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function escapeAttr(s=''){return escapeHtml(s)}
 function renderGallery(images,layout,cls){if(!images.length)return '<div class="portrait">PHOTO<br>COMING SOON</div>';let use=layout==='single'?images.slice(0,1):images;return `<div class="cmsPhotos ${cls} layout-${layout}">${use.map(im=>`<figure><img src="${escapeAttr(im.url)}" alt="${escapeAttr(im.caption||'Fresh & Ready by Dori')}">${im.caption?`<figcaption>${escapeHtml(im.caption)}</figcaption>`:''}</figure>`).join('')}</div>`}
})();
