window.SITE_DATA={
 "theme":{"green":"#064B3B","deep":"#033329","gold":"#C6A15B","silver":"#B8C0C2","cream":"#F5F2EA","ink":"#17201C","white":"#FFFDF8"},
 "version":7,
 "business":{"address1":"132 West Street","address2":"Boston, Lincolnshire","email":"freshandreadybydori@gmail.com","phone":"","hours":{"Monday":"05:00–17:00","Tuesday":"05:00–17:00","Wednesday":"05:00–17:00","Thursday":"05:00–17:00","Friday":"05:00–17:00","Saturday":"05:00–17:00","Sunday":"Closed"}},
 "text":{"announcement":"COMING SOON TO BOSTON • MONDAY–SATURDAY • FROM 5AM","heroEyebrow":"BOSTON • OPEN FROM 5AM","heroTitle":"Good Food. Brighter Days.","heroLead":"Fresh, filling food made for early mornings, busy days and people who like it their way.","heroMicro":"BIG FOOD • BUILD YOUR OWN • GREAT VALUE","menuEyebrow":"OUR MENU","menuTitle":"Big favourites. Everyday classics.","menuIntro":"From oversized Signature Giants to familiar bakery favourites and a completely customisable meal.","featuredEyebrow":"MADE TO BE NOTICED","featuredTitle":"Big food. Bold choice. Made your way.","buildEyebrow":"BUILD YOUR OWN","buildTitle":"Your breakfast. Your lunch. Your rules.","storyEyebrow":"OUR STORY","storyTitle":"Built for early mornings. Made for our community.","storyBody":"Fresh & Ready by Dori grew from something we experienced ourselves. We know what it feels like to start work very early and struggle to find fresh, filling food that you can actually make your own.\n\nSo we decided to create the place we wished had been there for us: open from 5AM, generous, flexible and welcoming.\n\nBut our purpose goes beyond the menu. We want to become part of the community we serve — a place where good food can make an ordinary day a little brighter.","manifesto":"More than food. A daily ritual.","communityEyebrow":"MORE THAN FOOD","communityTitle":"A place that gives something back.","teamEyebrow":"OUR TEAM","teamTitle":"Small team. Big purpose.","careersEyebrow":"CAREERS","careersTitle":"Build brighter days with us.","careersIntro":"Explore current opportunities at Fresh & Ready by Dori in Boston.","deliveryEyebrow":"DELIVERY","deliveryTitle":"Fresh & Ready, wherever your day takes you.","deliveryText":"Uber Eats and Just Eat ordering will be available here when our delivery channels go live.","allergenEyebrow":"FOOD INFORMATION","allergenTitle":"Allergies & intolerances","allergenText":"Please speak to a member of our team before ordering if you have a food allergy or intolerance. Final allergen information will be built from the exact recipes and supplier labels before opening.","findEyebrow":"FIND US","contactEyebrow":"CONTACT","contactTitle":"Say hello.","openingNote":"Opening date coming soon.","footerTagline":"Good Food. Brighter Days."},
 "hero":{"image":"","imageKey":"","alt":"Fresh & Ready by Dori","position":"center","overlay":"none"},
 "sections":[{"id":"hero","label":"Hero","visible":true},{"id":"quick","label":"Quick benefits","visible":true},{"id":"menu","label":"Menu","visible":true},{"id":"featured","label":"Featured products","visible":true},{"id":"build","label":"Build Your Own","visible":true},{"id":"story","label":"Our Story","visible":true},{"id":"manifesto","label":"Manifesto","visible":true},{"id":"community","label":"Community","visible":true},{"id":"team","label":"Our Team","visible":true},{"id":"careers","label":"Careers","visible":true},{"id":"delivery","label":"Delivery","visible":true},{"id":"allergens","label":"Allergens","visible":true},{"id":"visit","label":"Find Us","visible":true}],
 "menu":[
  {"id":"giants","name":"Signature Giants","description":"Intentionally oversized.","visible":true,"products":[
   {"id":"breakfast-beast","name":"English Breakfast Giant Burger","description":"A full breakfast stacked into one giant homemade bun.","price":"9.99","ingredients":"","calories":"","allergens":[],"image":"","available":true,"featured":true,"visible":true},
   {"id":"giant-donut","name":"Giant Baked Donut","description":"One glaze included. Then make it yours.","price":"3.99","ingredients":"","calories":"","allergens":[],"image":"","available":true,"featured":true,"visible":true}]},
  {"id":"classics","name":"Fresh & Ready Classics","description":"Comfort food, ready for the day.","visible":true,"products":[]},
  {"id":"drinks","name":"Drinks","description":"Hot, cold and made your way.","visible":true,"products":[]}
 ],
 "optionGroups":[{"id":"milk-choice","name":"Milk choice","min":1,"max":1,"options":[{"id":"whole","name":"Whole milk","price":"0.00","available":true},{"id":"semi","name":"Semi-skimmed milk","price":"0.00","available":true},{"id":"oat","name":"Oat milk","price":"0.50","available":true}]}],
 "builders":[
  {"id":"meal","name":"Build Your Own Meal","price":"6.99","description":"Fresh. Big. Just the way you like it.","visible":true,"steps":[{"id":"base","name":"Choose your base","min":1,"max":1,"options":[{"name":"COB","price":"0.00"},{"name":"BAGUETTE","price":"0.00"},{"name":"PANINI","price":"0.00"},{"name":"CRÊPE","price":"0.00"}]},{"id":"main","name":"Choose your main","min":1,"max":1,"options":[{"name":"House Beef Patty","price":"0.00"},{"name":"House Chicken Patty","price":"0.00"},{"name":"Sausage","price":"0.00"},{"name":"Crispy Chicken","price":"0.00"},{"name":"Ham","price":"0.00"}]}]},
  {"id":"cereal-bowl","name":"Build Your Own Cereal Bowl","price":"3.99","description":"Choose your cereal, milk and toppings.","visible":true,"steps":[{"id":"cereal","name":"Choose your cereal","min":1,"max":2,"options":[{"name":"Cereal 1","price":"0.00"},{"name":"Cereal 2","price":"0.00"},{"name":"Cereal 3","price":"0.00"},{"name":"Cereal 4","price":"0.00"}]},{"id":"milk","name":"Choose your milk","min":1,"max":1,"options":[{"name":"Whole milk","price":"0.00"},{"name":"Semi-skimmed milk","price":"0.00"},{"name":"Oat milk","price":"0.50"}]},{"id":"toppings","name":"Add toppings","min":0,"max":99,"options":[]}]}
 ],
 "buildYourOwn":{"price":"6.99","bases":["COB","BAGUETTE","PANINI","CRÊPE"],"mains":["House Beef Patty","House Chicken Patty","Sausage","Crispy Chicken","Ham"],"included":"Cheddar + fresh salad + up to 2 standard sauces included.","extras":"Egg, bacon, hash brown, extra cheese, potatoes, extra patties & more."},
 "deals":[],
 "community":[{"title":"10% COMMUNITY DISCOUNT","text":"For NHS staff, police and fire service personnel."},{"title":"10% SUPPORT DISCOUNT","text":"Planned for eligible disabled people, older people and children in care / care-experienced young people. Final eligibility and proof requirements will be published before launch."},{"title":"COMMUNITY BOARD","text":"A free local noticeboard for appropriate opportunities in employment, education and professional development."}],
 "team":[{"id":"managing-director","name":"Managing Director","role":"Managing Director","description":"Business, operations, customer experience and the Fresh & Ready vision.","visible":true},{"id":"chef","name":"Senior Chef & Pastry Chef","role":"Senior Chef & Pastry Chef","description":"Kitchen production, recipes, pastry and the food behind Fresh & Ready.","visible":true}],
 "galleries":{"staff":{"label":"Staff","layout":"grid","images":[]},"products":{"label":"Products","layout":"grid","images":[]},"ourStory":{"label":"Our Story","layout":"collage","images":[]},"premises":{"label":"Premises","layout":"grid","images":[]},"community":{"label":"Community","layout":"grid","images":[]},"promotions":{"label":"Promotions","layout":"grid","images":[]}},
 "careers":{"enabled":true,"talentPool":false,"jobs":[{"id":"kitchen-assistant","title":"Kitchen Assistant","department":"Kitchen","location":"Boston, Lincolnshire","employmentType":"Part-time","hours":"","pay":"","summary":"Join the opening team at Fresh & Ready by Dori.","responsibilities":"","requirements":"","offer":"","startDate":"","closingDate":"","status":"draft","featured":false,"visible":false}]},
 "delivery":{"uberEnabled":false,"uberLabel":"UBER EATS • COMING SOON","uberUrl":"","justEatEnabled":false,"justEatLabel":"JUST EAT • COMING SOON","justEatUrl":""},
 "seo":{"title":"Fresh & Ready by Dori | Boston","description":"Fresh, filling food from 5AM in Boston. Signature Giants, Build Your Own, classics and meal deals.","shareImage":"","instagram":"","facebook":"","tiktok":"","googleMaps":"https://www.google.com/maps/search/?api=1&query=132+West+Street+Boston+Lincolnshire"}
};
